### ISSUE TITLE
Style text, correct the white space

### ISSUE THREAD

**Issue by crodrgz** [state-matters/state-matters-website#32] opened 2018-06-09 20:37 UTC
Header should be Martel Light 32px
text buttons should be black

![image](https://user-images.githubusercontent.com/40127298/41195860-e08e25d4-6bfa-11e8-89f1-5d92c88d29b3.png)

**Comment by pkrawc** [comment] 2018-06-13 01:28
Duplicate of #34 

Let's combine all text sizing issues so we don't get unwieldy text styles in a 5 page application.

**Closed by pkrawc** 2018-06-13 01:28 UTC
